site_name: YAMLpp
site_description: A macro language for dynamic YAML preprocessing
docs_dir: docs   # source directory for documentation

theme:
  name: material
  icon:
    logo: material/code-tags
  language: en
  features:
    - navigation.sections
    - navigation.tabs
  palette:
    scheme: default
    primary: teal
    accent: teal

repo_url: https://github.com/fralau/yamlpp
edit_uri: edit/main/docs/
copyright: Â© Laurent Franceschetti, 2025. Licensed under CC BY-SA 4.0.

nav:
  - Home: index.md
  - Guide: guide.md
  - Modules: modules.md
  - Reference: reference.md
  - Advanced: advanced.md
  - Troubleshooting: troubleshooting.md

markdown_extensions:
  - admonition
  - footnotes
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true # necessary to make it work

plugins:
  - search

  